export const TURKISH_UNIVERSITIES = [
  'Abant İzzet Baysal Üniversitesi',
  'Abdullah Gül Üniversitesi',
  'Adıyaman Üniversitesi',
  'Afyon Kocatepe Üniversitesi',
  'Ağrı İbrahim Çeçen Üniversitesi',
  'Aksaray Üniversitesi',
  'Alanya Alaaddin Keykubat Üniversitesi',
  'Amasya Üniversitesi',
  'Ankara Hacı Bayram Veli Üniversitesi',
  'Ankara Üniversitesi',
  'Ankara Yıldırım Beyazıt Üniversitesi',
  'Ardahan Üniversitesi',
  'Artvin Çoruh Üniversitesi',
  'Atatürk Üniversitesi',
  'Atılım Üniversitesi',
  'Bahçeşehir Üniversitesi',
  'Balıkesir Üniversitesi',
  'Bandırma Onyedi Eylül Üniversitesi',
  'Bartın Üniversitesi',
  'Batman Üniversitesi',
  'Bayburt Üniversitesi',
  'Bilecik Şeyh Edebali Üniversitesi',
  'Bingöl Üniversitesi',
  'Bitlis Eren Üniversitesi',
  'Boğaziçi Üniversitesi',
  'Bolu Abant İzzet Baysal Üniversitesi',
  'Burdur Mehmet Akif Ersoy Üniversitesi',
  'Bursa Teknik Üniversitesi',
  'Bursa Uludağ Üniversitesi',
  'Çanakkale Onsekiz Mart Üniversitesi',
  'Çankırı Karatekin Üniversitesi',
  'Çukurova Üniversitesi',
  'Dicle Üniversitesi',
  'Dokuz Eylül Üniversitesi',
  'Düzce Üniversitesi',
  'Ege Üniversitesi',
  'Erciyes Üniversitesi',
  'Erzincan Binali Yıldırım Üniversitesi',
  'Erzurum Teknik Üniversitesi',
  'Eskişehir Osmangazi Üniversitesi',
  'Eskişehir Teknik Üniversitesi',
  'Fırat Üniversitesi',
  'Galatasaray Üniversitesi',
  'Gazi Üniversitesi',
  'Gaziantep Üniversitesi',
  'Gaziosmanpaşa Üniversitesi',
  'Gebze Teknik Üniversitesi',
  'Giresun Üniversitesi',
  'Gümüşhane Üniversitesi',
  'Hacettepe Üniversitesi',
  'Hakkari Üniversitesi',
  'Harran Üniversitesi',
  'Hitit Üniversitesi',
  'Iğdır Üniversitesi',
  'Isparta Uygulamalı Bilimler Üniversitesi',
  'İnönü Üniversitesi',
  'İskenderun Teknik Üniversitesi',
  'İstanbul Üniversitesi',
  'İstanbul Teknik Üniversitesi',
  'İstanbul Medeniyet Üniversitesi',
  'İzmir Kâtip Çelebi Üniversitesi',
  'İzmir Yüksek Teknoloji Enstitüsü',
  'Kafkas Üniversitesi',
  'Kahramanmaraş Sütçü İmam Üniversitesi',
  'Kahramanmaraş İstiklal Üniversitesi',
  'Karabük Üniversitesi',
  'Karadeniz Teknik Üniversitesi',
  'Karamanoğlu Mehmetbey Üniversitesi',
  'Kars Kafkas Üniversitesi',
  'Kastamonu Üniversitesi',
  'Kayseri Üniversitesi',
  'Kilis 7 Aralık Üniversitesi',
  'Kırıkkale Üniversitesi',
  'Kırklareli Üniversitesi',
  'Kırşehir Ahi Evran Üniversitesi',
  'Kocaeli Üniversitesi',
  'Konya Teknik Üniversitesi',
  'Cumhuriyet Üniversitesi',
  'Malatya Turgut Özal Üniversitesi',
  'Manisa Celal Bayar Üniversitesi',
  'Mardin Artuklu Üniversitesi',
  'Mersin Üniversitesi',
  'Middle East Technical University (ODTÜ)',
  'Muğla Sıtkı Koçman Üniversitesi',
  'Munzur Üniversitesi',
  'Muş Alparslan Üniversitesi',
  'Nevşehir Hacı Bektaş Veli Üniversitesi',
  'Niğde Ömer Halisdemir Üniversitesi',
  'Ondokuz Mayıs Üniversitesi',
  'Ordu Üniversitesi',
  'Osmaniye Korkut Ata Üniversitesi',
  'Pamukkale Üniversitesi',
  'Recep Tayyip Erdoğan Üniversitesi',
  'Sabancı Üniversitesi',
  'Sakarya Üniversitesi',
  'Selçuk Üniversitesi',
  'Siirt Üniversitesi',
  'Sinop Üniversitesi',
  'Sivas Cumhuriyet Üniversitesi',
  'Şırnak Üniversitesi',
  'Tekirdağ Namık Kemal Üniversitesi',
  'Tokat Gaziosmanpaşa Üniversitesi',
  'Trabzon Üniversitesi',
  'Tunceli Munzur Üniversitesi',
  'Türk-Alman Üniversitesi',
  'Uşak Üniversitesi',
  'Van Yüzüncü Yıl Üniversitesi',
  'Yalova Üniversitesi',
  'Yıldız Teknik Üniversitesi',
  'Zonguldak Bülent Ecevit Üniversitesi',
];

export const ACADEMIC_DEPARTMENTS = [
  'Bilgisayar Mühendisliği',
  'Bilgisayar Programcılığı',
  'Bilgisayar ve Bilişim Bilimleri',
  'Yazılım Mühendisliği',
  'Elektrik-Elektronik Mühendisliği',
  'Elektronik ve Haberleşme Mühendisliği',
  'Makine Mühendisliği',
  'Endüstri Mühendisliği',
  'İnşaat Mühendisliği',
  'Kimya Mühendisliği',
  'Metalurji ve Malzeme Mühendisliği',
  'Mekatronik Mühendisliği',
  'Biyomedikal Mühendisliği',
  'Çevre Mühendisliği',
  'Gıda Mühendisliği',
  'İşletme',
  'İktisat',
  'Muhasebe ve Finans Yönetimi',
  'Uluslararası Ticaret',
  'Yönetim Bilişim Sistemleri',
  'Pazarlama',
  'İnsan Kaynakları Yönetimi',
  'Hukuk',
  'Psikoloji',
  'Sosyoloji',
  'Mimarlık',
  'İç Mimarlık',
  'Grafik Tasarım',
  'Endüstriyel Tasarım',
  'Tıp',
  'Hemşirelik',
  'Eczacılık',
  'Diş Hekimliği',
  'Matematik',
  'Fizik',
  'Kimya',
  'Biyoloji',
  'İstatistik',
  'Veri Bilimi',
  'Yapay Zeka ve Veri Mühendisliği',
  'Bilişim Sistemleri Mühendisliği',
  'Ağ ve Siber Güvenlik',
];
